### PR TITLE
Clean up some tests

### LINKED ISSUE #731: Clean up some tests
I noticed that these tests could benefit some rewrite, especially using `async function`s to make them much more readable and maintainable: `test/test-init-shutdown.js` & `test/test-logging.js`.

### PR DESCRIPTION
**Pull request by felixdivo**
This:
- roughly cuts the changed code length in half,
- is *much* more readable thanks to `async` code,
- uses strict comparisons,
- has better error messages/test titles,
- is less duplicated, and
- does not really change *what* is tested.

Closes #731

### CODE REVIEW

**Comment by felixdivo** [comment]
Hm, strange. I think this is done, but there's this error: `FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.` on CircleCI and AppVeyor. Has it appeared before? And Travis is failing too, but seemingly unrelated.

**Comment by wayneparrott** [comment]
@felixdivo I took a quick look and think the problem might be at line 55 in test-logging.js. 
image

My reasoning is that the code where the exception is occurs is: 
```
// preprocess Context
  RclHandle* context_handle = RclHandle::Unwrap<RclHandle>(
      Nan::To<v8::Object>(info[0]).ToLocalChecked());
```

**Comment by minggangw** [comment]
Hi @felixdivo would you please create the corresponding issues for this PR and #726, so we could track through issue<->pull request, thanks!

**Comment by minggangw** [comment]
> My reasoning is that the code where the exception is occurs is:
> 
> ```
> // preprocess Context
>   RclHandle* context_handle = RclHandle::Unwrap<RclHandle>(
>       Nan::To<v8::Object>(info[0]).ToLocalChecked());
> ```

That's right, we have to pass an instance of Context as the 1st parameter.

**Comment by felixdivo** [comment]
Thanks @wayneparrott! It was exactly there. I was fooled by the default value for the `context` parameter, which (somewhat obviously) isn't used when passing an argument. It's now fixed. I'll check if the rest now works.

**Comment by felixdivo** [comment]
> would you please create the corresponding issues for this PR and #726

Done.

And this PR is ready for a review.

**Review by minggangw — APPROVED** [review]
Thanks for simplifying the tests! lgtm

**Pull request merged**
