### PR TITLE
Fix build in cases where AMENT_PREFIX_PATH has more than two items

### PR DESCRIPTION
**Pull request by amikhalev**

### CODE REVIEW

**Comment by minggangw** [comment]
Thanks for your patch! I noticed there are some test failures on CI which may be caused by the latest change of the ROS2 nightly build. So I am going to fix it first, then you can rebase your patch and trigger the  CI again, thanks!

**Review by minggangw — APPROVED** [review]
Code LGTM. A suggestion about the commit log, would you please give a concrete description about what this patch is going to fix:

1. The current problem, better with an example.
2. What happens after this patch.

**Comment by minggangw** [comment]
I forgot you can also add yourself as a contributor as https://github.com/RobotWebTools/rclnodejs/pull/509/files#diff-04c6e90faac2675aa89e2176d2eec7d8R154 did.

**Comment by amikhalev** [comment]
Thank you for the suggestions, I've implemented them. Will rebase once you push to develop

**Comment by minggangw** [comment]
@amikhalev The test cases have been updated accordingly and all the CIs are passing now. Please rebase with the `develop` branch again, thanks!

**Comment by minggangw** [comment]
Thanks for your effort @amikhalev, I am going to merge this PR.

**Pull request merged**
