### PR TITLE
Upgrade Node.js to LTS Erbium

### PR DESCRIPTION
**Pull request by minggangw**
Fix #None

### CODE REVIEW

**Comment by minggangw** [comment]
Currently, we cannot get passed on the latest Erbium which is v12.13.0 due to the incompatibility of [ref](https://www.npmjs.com/package/ref). So if we want to upgrade the Node.js in the future, we have to cope with this problem.

**Comment by minggangw** [comment]
We also update the README to illustrate this, see 90ebf88b1298258c33ed290c5c2a030b0be9b312

**Comment by minggangw** [comment]
I found some alternatives which support N-API, please check them out below:

- [ref-napi](https://github.com/node-ffi-napi/ref-napi)
- [ref-array-di](https://github.com/node-ffi-napi/ref-array-di)
- [ref-struct-di](https://github.com/node-ffi-napi/ref-struct-di)

I think we can replace the old `ref` series if we want to support a higher version of Node.js, e.g. Erbium

**Comment by mattrichard** [comment]
@minggangw Once #582 goes in we should see if the CI builds pass in this PR.

**Comment by minggangw** [comment]
Thanks, I am going to rebase and run the CIs again when it's landed.

**Comment by minggangw** [comment]
Everything goes well! Thanks for fixing all the errors @mattrichard

**Pull request merged**
