### PR TITLE
ROS 2.0 Time features

### PR DESCRIPTION
**Pull request by kenny-y**
Task remaining:
 - jsdoc document
 - steady-clock type support
Will open issues to track remaining tasks

### CODE REVIEW

**Review by minggangw — APPROVED** [review]
Thanks for implementing this feature so quickly!

**Comment by kenny-y** [comment]
It looks like SIGSEV was caught (exit code 139) each time executing `coverall` on Mac, any ideas? @minggangw

**Comment by minggangw** [comment]
I checked the ` Segmentation fault: 11` error, it means that too large memory has been allocated on stack. I suppose some unit test triggering that case perhaps.

**Comment by qiuzhong** [comment]
I guess this PR needs to rebase now.

**Comment by minggangw** [comment]
I am going to close this PR, as the relative feature has changed a lot in rcl library.

**Pull request closed without merging**
