### PR TITLE
Remove invalid import

### PR DESCRIPTION
**Pull request by wayneparrott**
Fixes Windows CI build error.

### CODE REVIEW

**Comment by wayneparrott** [comment]
Thoughts on the the frequent CI test failure to detect the hidden node used by Rate in test-rate.js test suite? We could add a bit of delay between Rate creation and request for nodes if you think that will improve reliability of this test. 
```
1) rclnodejs rate test suite
       rate server node naming test:
```

**Comment by minggangw** [comment]
Of course, we should add it to reduce the failures. Another option, we can add the flaky test into https://github.com/RobotWebTools/rclnodejs/blob/develop/test/blacklist.json based on a specific platform to disable a test. But I think adding a delay is enough.

**Comment by wayneparrott** [comment]
Fingers crossed the 1 sec delay improves the reliability of the rate test suite across all CI envs.

**Review by minggangw — APPROVED** [review]
Thanks for fixing this, merging.

**Pull request merged**
