### PR TITLE
Improves typing support for clients and services

### LINKED ISSUE #708: Improve typing support for services
**Problem**
When working with Services in TypeScript the type definitions use semi-ambiguous Message[T] rather than the more precise MessageType<T>. @mattrichard implementation of action typing demonstrate how to create unambiguous typing definitions. A similar technique could be used to improve the typing definitions of Services and Clients.

**Proposal**
This enhancement request proposes to apply the generics patterns used in the action typings to improve the Service and Client and related callback and handler definitions. The changes should should be backward compatible.

**Expected outcome** 
The results should be much more precise service and client typings that smart typescript editors (e.g., VSCode) can employ to assist developers create clean, unambiguous services and clients.

### PR DESCRIPTION
**Pull request by wayneparrott**
Improve client and service typing support.

Key changes
* Converted the following main typescript classes created by Node to
interfaces: Client, Entity, GuardCondition, Publisher, Rate,
Subscription
* Refactored Client and Service to generic interfaces
* Refactored rostsd_gen/index.js to produce ServiceConstructors, Service
and ServiceType types. All maps are generated with keys in alphabetical
order. Also cleaned up the flow and improved consistency of the code.
* Updated service and client tests in test/type/main.ts

Fix #708

### CODE REVIEW

**Comment by wayneparrott** [comment]
Fixing the build error asap. I did not have test_interface_files pkg installed in my dev env. 

update-1: At 1st glance, file generation from the generate_message is not generating the service msgs (<srv>_Request and <srv>_Response) for any of the test_interface_files/srv/*.srv files. The [test_interface_files pkg](https://github.com/ros2/test_interface_files) has not been updated for over 13+ months. The [test_msgs pkg](https://github.com/ros2/rcl_interfaces) appears to be the replacement for test_interface_files has been updated as recently as yesterday and is processed with no issues by the generate_messages script. 

**I plan to look into the generate_messages issue with test_interface_files pkg but would like to ask if we need to test against this package since test_msgs pkg seems to be the one we should focus on in testing?** 

update-2: Upon inspecting the diffs between test_interface_files pkg and the test_msgs pkg, the services in the test_interface_files pkg do not include the <srv>_Request.msg and <srv>_Response.msg files. The test_msgs pkg includes these missing files. I believe the root issue is the test_interface_files pkg is not correctly configured in its package.xml. **Conclusion: the test_interface_files pkg is goofed and tsd_gen script should do a better job at identifying goofed up interfaces.**

**Comment by minggangw** [comment]
Thanks for making the improvements for ts, I investigated the error reported on trybot

```bash
Caught error: Error: Cannot find module './test_interface_files__srv__Arrays_Request.js'
Require stack:
- C:\proj\rclnodejs\generated\test_interface_files\test_interface_files__srv__Arrays.js
- C:\proj\rclnodejs\lib\interface_loader.js
- C:\proj\rclnodejs\rostsd_gen\index.js
- C:\proj\rclnodejs\scripts\generate_messages.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
```

Just as you have mentioned in **update-2**  that the services in the test_interface_files pkg don't include the _Request.msg and _Response.msg files, so the idl_generator doesn't generate the corresponding JS files for them. Because the `test_interface_files ` has been deprecated, I think that's the reason why there is no _Request/Response.msg files, unfortunately, the `.srv` is still there.

Some comments based on your latest update

> Conclusion: the test_interface_files pkg is goofed and tsd_gen script should do a better job at identifying goofed up interfaces.

Strongly agree, probably we could just check if the  _Request/Response.msg exist practically.

**Comment by wayneparrott** [comment]
Added checks for actions and services to verify that the required interfaces are present before generating the respective tsd info. When an invalid service or action is detected (e.g., test_interface_files/srv/*) an informative error msg is output to stdout and the invalid interface is not included in the interfaces.d.ts file.

**Review by minggangw — APPROVED** [review]
Thanks for refactoring the generation for ts, LGTM!

**Comment by minggangw** [comment]
After landing this PR, I think v0.16.0 is ready to publish, thanks for your effort!

**Pull request merged**
