### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by IsabelParedes**
**Public API Changes**

None

**Description**

This PR simply fixes a few typos in the documentation.

### CODE REVIEW

**Review by wayneparrott — APPROVED** [review]
lgtm

**Comment by wayneparrott** [comment]
@ihuicatl thx for the type fixes. much appreciated. 
OT - ros2wasm looks interesting. I've wondered about use of wasm in ros for awhile.

**Comment by IsabelParedes** [comment]
Hi @wayneparrott, thanks for the review! 
I was actually looking into possibly integrating `rclnodejs` into the `ros2wasm` project. So if you have any tips I'd be pretty interested :)

**Comment by minggangw** [comment]
@ihuicatl thanks for fixing the typos!

**Review by minggangw — APPROVED** [review]

**Comment by minggangw** [comment]
> Hi @wayneparrott, thanks for the review! I was actually looking into possibly integrating `rclnodejs` into the `ros2wasm` project. So if you have any tips I'd be pretty interested :)

Never think about compiling `rclnodejs` to wasm, interesting! I'm not clear how you can deal with the addon written in C++, please update us if you have progress :) By the way, is there any motivation for you to leverage wasm?

**Comment by IsabelParedes** [comment]
Hi @minggangw! Currently the motivation is from an educational perspective. I worked on setting up a ROS environment with JupyterHub for a university course before, and having a ROS environment run entirely on the browser would be a step up from that. 
Right now I have some publisher and subscriber nodes running on the browser but I'm looking to add more interaction which is where integrating `rclnodejs` would be really nice to have. 
For the addon in C++, that should be compile-able with Emscripten which is how I've been compiling the rest of the ROS packages. I think I'll have to figure out how to detect my wasm modules as a valid ROS installation though.

**Comment by minggangw** [comment]
@ihuicatl I see, that makes sense. Have you tried with [roslibjs](https://github.com/RobotWebTools/roslibjs), which can support ROS2 on the browser, or Electron? Because both can save a lot of effort if you want to enable ROS2 on the browser.

**Comment by IsabelParedes** [comment]
Hi @minggangw, I took a look at `roslibjs` before but wasn't sure if it supported ROS2 since I only saw one `ros2` branch. But `roslibjs` seems to rely on a `rosbridge` connection to a native ROS installation, which I feel like I would run into the same problem that I'd have to figure out how to connect `roslibjs` to wasm modules without relying on a native ROS installation nor `rosbridge`.
I haven't used Electron before but that seems more for creating desktop applications which is not exactly what I'm trying to do. I'm simply trying to have ROS2 run on a website without requiring any installations by the user.

**Pull request merged**
