### PR TITLE
Complete the test cases for missing rclnodejs APIs

### PR DESCRIPTION
**Pull request by qiuzhong**
* Complete test cases rclnodejs.validator family APIs (+11)
* Add 2 test cases for the case when the publisher/subscription are in the same process.

### CODE REVIEW

**Comment by qiuzhong** [comment]
Please don't merge this PR as I'll add more test cases after #148 fixed.

**Comment by minggangw** [comment]
Got it, I am working on #148 now.

**Comment by qiuzhong** [comment]
@minggangw , test cases for #148 had been added.

**Comment by minggangw** [comment]
Thanks, merging...

**Pull request merged**
