### PR TITLE
Complete the C++ - rclnodejs message types test cases

### PR DESCRIPTION
**Pull request by qiuzhong**
Add 36 test cases for C++ - rclnodejs message types communication.

### CODE REVIEW

**Comment by qiuzhong** [comment]
@minggangw , the Windows CI failed because of the `ament.py build` was not executed in a VS2017 build tools environment. I didn't know how to load this in the `appvevor.yml`. Can you take a look and give me some advice?

**Comment by minggangw** [comment]
Sure  :smiley:

**Comment by minggangw** [comment]
@qiuzhong please try to add the line below:

```
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
```

**Comment by qiuzhong** [comment]
Thanks! I'll try it.

**Comment by qiuzhong** [comment]
@minggangw , it turns out that the ros2 release package for Windows has no ament build tools at all! I'm trying to find a  workaround.

**Comment by qiuzhong** [comment]
My bad, I'll use the `ament` binary build tools and update this PR.

**Comment by minggangw** [comment]
Never mind, just go ahead :smiley:

**Comment by minggangw** [comment]
Thanks for the great work to realize these tests to verify the whole project's compatibilities, that's something and merging.

**Pull request merged**
