### PR TITLE
Add test cases for M3 legacy features

### PR DESCRIPTION
**Pull request by qiuzhong**
* Add 2 test cases for MultiArray message type.
* Add 2 test cases for rclpy - rclnodejs client/service interaction.

### CODE REVIEW

**Comment by qiuzhong** [comment]
Looks like there are some problems, I'm fixing them.

**Comment by minggangw** [comment]
LGTM, I will merge this PR after #144 has been fixed, thanks!

**Comment by minggangw** [comment]
As #144 has been fixed, merge this one.

**Comment by qiuzhong** [comment]
Thanks!

**Pull request merged**
