### PR TITLE
Add node 13-17 support, bump to v0.21.0

### LINKED ISSUE #735: Compilation warning on newer node versions: v8 has a new ArrayBuffer BackingStore API
I get this output by `node-gyp rebuild` (invoked using `scripts/build.sh`) on Node version `v14.10.1`:

```
../src/rcl_bindings.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE rclnodejs::CreateArrayBufferFromAddress(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/rcl_bindings.cpp:1330:70: warning: ‘static v8::Local<v8::ArrayBuffer> v8::ArrayBuffer::New(v8::Isolate*, void*, size_t, v8::ArrayBufferCreationMode)’ is deprecated: Use the version that takes a BackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
 1330 |                            v8::ArrayBufferCreationMode::kInternalized);
      |                                                                      ^
In file included from /home/felix/.cache/node-gyp/14.10.1/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/rcl_bindings.hpp:18,
                 from ../src/rcl_bindings.cpp:15:
/home/felix/.cache/node-gyp/14.10.1/include/node/v8.h:5169:29: note: declared here
 5169 |   static Local<ArrayBuffer> New(
      |                             ^~~
../src/rcl_bindings.cpp:1330:70: warning: ‘static v8::Local<v8::ArrayBuffer> v8::ArrayBuffer::New(v8::Isolate*, void*, size_t, v8::ArrayBufferCreationMode)’ is deprecated: Use the version that takes a BackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
 1330 |                            v8::ArrayBufferCreationMode::kInternalized);
      |                                                                      ^
In file included from /home/felix/.cache/node-gyp/14.10.1/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/rcl_bindings.hpp:18,
                 from ../src/rcl_bindings.cpp:15:
/home/felix/.cache/node-gyp/14.10.1/include/node/v8.h:5169:29: note: declared here
 5169 |   static Local<ArrayBuffer> New(
      |                             ^~~```
```

I didn't include it in #734 as I don't really know any v8 internals.

### PR DESCRIPTION
**Pull request by wayneparrott**
**Public API Changes**
none

**Description**

0. package.json
* Bumped to version 0.21.0
* Support for node 13-16 required forking and customizing the following
packages:
@rclnodejs/ref-array-di
@rclnodejs/ref-napi
@rclnodejs/ref-struct-di
Revised package dependencies to use the 3 packaged listed above
* Added jsdoc as devDependency

2. test-security-related.js
* Fixed minor assertion error caused by change in Nodejs error message.

3. Docs
* Updated README.md, Build.md and npmjs-readme.md to expand valid
versions of node 13-16.
* Modified docs/Makefile to use npx to run jsdoc to generate api
documentation

Fix #735 #717

### CODE REVIEW

**Comment by wayneparrott** [comment]
On linux running install with node16 as root is a PIA with permissions issues. No such issues with node 12 & 14. Thus the zillion commits as I slowly convert from running scripts and test suite to non-root user. Grant me patience!

**Comment by felixdivo** [comment]
In the very beginning of [`README.md`](https://github.com/RobotWebTools/rclnodejs/blob/develop/README.md), the `node` tag still mentions the old version restriction.

**Comment by wayneparrott** [comment]
@felixdivo hi, the node tag is dynamically generated from https://img.shields.io/node/v/rclnodejs. When we publish the next rclnodejs release to npmjs.com the tag should be updated with the latest range of supported node versions.

**Comment by felixdivo** [comment]
Ah okay, sorry for the bump.
Neat! 😃

**Comment by minggangw** [comment]
There is an update, saying that this crash issue (from node v13 to v16) has been fixed on [node v17](https://github.com/node-ffi-napi/ref-napi/issues/54#issuecomment-1009940294), but with performance regression. @wayneparrott

**Comment by minggangw** [comment]
I verify rclnodejs v0.20.1 with node v17.4.0 and the crash is gone.

**Comment by wayneparrott** [comment]
> I verify rclnodejs v0.20.1 with node v17.4.0 and the crash is gone

Was this build using the original `ref-napi` and related packages or did you use the forked and udpated @rclnodejs/ref-napi and related packages?

**Comment by Zaaler** [comment]
I'm running rclnodejs v0.21.0 with node v17.8.0 on aarch64 and ros2 galactic and I'm experiencing the cannot reinterpret from nullptr pointer.

I found a work around earlier but, I've since flashed the computer and now, I'm unfortunately debugging something I already solved. I think I may have reverted node to 16 and used the previously mentioned solution.

Should I be experiencing this error still?

**Pull request merged**
