### PR TITLE
Adding ROS Node test suite and ROS Publisher test suite

### PR DESCRIPTION
**Pull request by kenny-y**
Not much test cases for now... expecting more in the future. e.g. for publisher, a meaningful test case would have been done with subscription being present.

### CODE REVIEW

**Comment by jihoonl** [comment]
@kenny-y @minggangw hey guys. I just wanted to let you know that I have invited both of you to `ROS2.0` team in RWT. Thanks for the works!

**Comment by kenny-y** [comment]
@jihoonl Yep, just saw that. Thanks for the invitation. We just get started on this repo, will let you know when there is any solid output...

**Comment by minggangw** [comment]
I have accepted the invitation and thanks, hope we together can make this happen soon :smile:

**Review by minggangw — APPROVED** [review]
lgtm and merge.

**Pull request merged**
