### PR TITLE
Add security-related tests for rclnodejs

### PR DESCRIPTION
**Pull request by qiuzhong**
* Destroy non-existent nodes (+6)
* Fuzzing API calls (+9)

### CODE REVIEW

**Comment by qiuzhong** [comment]
Due to #241 and #243 , please don't merge this PR now.

**Comment by minggangw** [comment]
Are we waiting for the #241 and #243 to be fixed?

**Comment by qiuzhong** [comment]
Yes.  I think so.

**Comment by qiuzhong** [comment]
This PR needs to update as #274 was verified.

**Comment by qiuzhong** [comment]
@minggangw , CI passed.

**Comment by minggangw** [comment]
I will merge the PR when all CIs are done, good job @qiuzhong !

**Pull request merged**
