### PR TITLE
[actionlib]Implement the actionlib on ROS 2.0

### LINKED ISSUE #314: Add the actions feature in rclnodejs
We want to support and expose the [actionlib](http://wiki.ros.org/actionlib) interfaces by leveraging the [actionlib_nodejs](https://github.com/RethinkRobotics-opensource/actionlib_nodejs), which is an implementation of actionlib on ROS and ROS2. A another issue https://github.com/RethinkRobotics-opensource/actionlib_nodejs/issues/2 is tracking this task on the repo.

### PR DESCRIPTION
**Pull request by minggangw**
The actionlib stack provides a standardized interface for interfacing
with preemptable tasks in the current ROS 1.0. By leveraging the
actionlib_nodejs module, we migrate this feature to ROS 2.0 platform and
expose it through rclnodejs client.

This patch implements:

- The interfaces which wraps the client/server functions.
- Expose and configure the actionlib module in rclnodejs.
- Examples to show the usage of actionlib.

To understand the whole picture of actionlib, please visit
http://wiki.ros.org/actionlib/DetailedDescription

Fix #314

### CODE REVIEW

**Comment by qiuzhong** [comment]
@minggangw , I failed to run the actionlib examples. Here are my trying steps:

* `source <path/to/ros2-linux>/local_setup.bash` (I get the ros2-linux package from a successful build CI release recently)
* Append `ros1_actions` directory to `AMENT_PREFIX_PATH`
* `npm install` in `rclnodejs-1` directory
* Run `actionlib-server-example.js` and I got this error:
  > Error: type_support argument is null, at /home/rosbuild/ci_scripts/ws/src/ros2/rcl/rcl/src/rcl/subscription.c:65
    at Function.createSubscription (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/subscription.js:42:28)
    at ShadowNode.createSubscription (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/node.js:198:37)
    at new ActionServerInterface (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/actions/action_server_interface.js:31:41)
    at ActionServer.start (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/node_modules/actionlibjs/lib/ActionServer.js:52:25)
    at rclnodejs.init.then (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/example/action-server-example.js:70:6)
    at <anonymous>

I entered to the `generated` directory and `ros1_actions` and related js files are all generated.

**Comment by qiuzhong** [comment]
Another concern is that the actionlib examples require `ros1_actions/msg/DoDishes` message, which is generated by `ros1_action/DoDishes.action` in the `AMENT_PREFIX_PATH`. However, this msg file is not include in `ros2-linux` package by default. There is a `dodishes_action` directory that contains the action  file in `test` directory but doesn't match `ros1_actions`.

If any users forgot to include this msg file in `AMENT_PREFIX_PATH` then this error will come out:

```
Error: The message required does not exist: ros1_actions, msg, DoDishesActionGoal
    at Object.loadInterface (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/interface_loader.js:99:11)
    at Object.loadInterfaceByString (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/interface_loader.js:46:19)
    at Object.loadInterface (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/interface_loader.js:86:21)
    at ShadowNode.createSubscription (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/node.js:190:26)
    at new ActionServerInterface (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/lib/actions/action_server_interface.js:31:41)
    at ActionServer.start (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/node_modules/actionlibjs/lib/ActionServer.js:52:25)
    at rclnodejs.init.then (/home/qiuzhong/Workspace/Work/ros4pr/rclnodejs_pr370/rclnodejs-1/example/action-server-example.js:70:6)
    at <anonymous>
```

In another word, the actionlib examples are not available after `npm install` with zeror configuration.

**Comment by minggangw** [comment]
As the `ros1_actions` is a project generated by `rclnodejs`, you have to run `colcon build` to compile the c code, then `source local_setup.bash`, which locates under `install` folder, to add its path to the variable ` AMENT_PREFIX_PATH`. After all these are done, you can re-run the example to test.

I will write a detailed instruction about the steps you must do.

**Comment by minggangw** [comment]
Please follow:

1.  Generate `.msg` from `.action` file.
2.  Switch to the folder which contians the `.action`, you will find a `CMakeList.txt` and run `colcon build`
3. `source install/local_setup.bash` which is created by step 2.
4.  Run the actionlib example again. (please make sure that steps 3&4 are the same console)

**Comment by qiuzhong** [comment]
@minggangw , thanks for the guide. The action examples are able to execute without errors now. I feel like the examples are quite troublesome for users. We should complete the README with all details.

**Pull request merged**
