### PR TITLE
Add actionlib tutorial

### PR DESCRIPTION
**Pull request by qiuzhong**
* Add a README to guide how to run the action example
* Rename the `dodishes_action` directory to `ros1_actions`
* Move example/README.md to tutorials/actionlib.md

Fix: #371 #373

### CODE REVIEW

**Comment by minggangw** [comment]
Hi @qiuzhong thanks for the effort to write an understandable document, I'd like to create a folder named `tutorials` under the root and put a link in the [README](https://github.com/RobotWebTools/rclnodejs/blob/develop/README.md) to hold this document. And I will make this ready in #370, so please rebase this PR when the #370 is merged.

**Comment by qiuzhong** [comment]
@minggangw , got it. I'll rebase it when #370 is merged.

**Comment by minggangw** [comment]
Hi @qiuzhong #370 has been merged, please migrate your README to the [actionlib.md](https://github.com/RobotWebTools/rclnodejs/blob/actionlib/tutorials/actionlib.md). As we want to have a complete tutorial, more information needs to be added, I list some points in my mind. Please reference it and the current ROS 1.0 [tutorial](http://wiki.ros.org/actionlib/Tutorials)

- A brief background of the actionlib in ROS (http://wiki.ros.org/actionlib/DetailedDescription)
- Prerequisites (the content of `.action` file)
- How to generate the `.msg` from `.action`, including add the path of `.action` into the environmental variable.
- How to compile the generated the `.so` library from the C++ codes in step 2, including source the `local_setup.bash` to add to the environmental variable.
- How to run the examples, explain the meaning of some typical code snippet.

Thanks a lot!

**Comment by qiuzhong** [comment]
As discussed, the `example/README.md` will be moved to `tutorials/actionlib.md` and more detailed guide will be added to it.

**Comment by minggangw** [comment]
I have cherry-pick 619cc195a35fb5e9ea into `actionlib` branch.

**Comment by qiuzhong** [comment]
Thanks! I'll rebase it.

**Comment by qiuzhong** [comment]
@minggangw , I just found the `postinstall` npm script doesn't work on actionlib branch. It said `../rosidl_gen/generator.js` was not found. Maybe the `rosidl_gen` was refactored on develop branch before?

**Comment by minggangw** [comment]
I am working on it and will be resolved soon, the root cause is a re-factoring work on `actionlib` branch which make it incompatible with `develop`.

**Comment by minggangw** [comment]
@qiuzhong this PR looks good to me, if it has been done, I will merge after your confirmation.

**Comment by minggangw** [comment]
Ping @qiuzhong

**Comment by qiuzhong** [comment]
@minggangw , I have completed the tutorial. Please merge it if you have no more concerns.

**Comment by minggangw** [comment]
Great! I am going to merge it soon :+1:

**Comment by minggangw** [comment]
As the environmental requirements have been changed a lot, I prefer to merge this PR directly to `develop` branch after the merging of `develop` with `actionlib`.

**Comment by minggangw** [comment]
Hi @qiuzhong as the `actionlib` has been merged into `develop`, would you please rebase this PR on `develop` branch and update it, thanks!

**Comment by qiuzhong** [comment]
Sure. I'll update it soon.

**Comment by qiuzhong** [comment]
@minggangw , updated and ready to merge.

**Comment by minggangw** [comment]
Thanks, I am going to merge it! Thanks!

**Pull request merged**
