### PR TITLE
Upgrade deep-equal and mkdirp

### PR DESCRIPTION
**Pull request by minggangw**
This patch upgrades deep-equal and mkdirp to the latest stable versions.

Fix #None

### CODE REVIEW

**Comment by minggangw** [comment]
Based on the latest `deep-equal` (2.0.1), the following returns `false`

```JavaScript
deepEqual([ 8, 9, 6, 4 ], Float64Array.from([ 8, 9, 6, 4 ]))
```
So we must figure it out, keep the current version or change the cases.

**Comment by mattrichard** [comment]
> So we must figure it out, keep the current version or change the cases.

I'm always for keeping dependencies up-to-date. One thing though, do we really need the library? Does it's perf benefits make any noticeable difference?

**Comment by minggangw** [comment]
> Does it's perf benefits make any noticeable difference?

Yes, it's said that "This module is around 46 times faster than wrapping assert.deepEqual() in a try/catch."

**Comment by mattrichard** [comment]
This gets even worse in Node.js v12. The following will now return false.

```javascript
assert.deepEqual([ 8, 9, 6, 4 ], Float64Array.from([ 8, 9, 6, 4 ]))
```

Actually, this change to `assert.deepEqual` is actually the reason why deep-equal's behavior was updated. Also, assert.deepEqual is deprecated in v12 (in favor of deepStrictEqual).

Looks like we're going to have to rely on deep-equal more if we want to continue using non-strict comparisons. As part of nodejs v12 support we should replace all assert.deepEqual with deep-equal. It's up to you whether we should update deep-equal or not.

**Comment by minggangw** [comment]
It seems that we only have one case that's not compatible with the latest `deep-equal`, which is the comparison of `Array` with `TypedArray`. How about offering a util method to handle it (compare the value by index), and then we can use the `deep-equal` for the others? The downside is we will lose some performance when running the test cases.

**Comment by minggangw** [comment]
Please ignore my last comment, I misunderstood. I suppose if we want to carry out this kind of comparison we need to keep the `deep-equal` @1.1.1, otherwise, we have to customize our own `deepEqual`.

I'd like to move `deep-equal` to `devDependencies` and keep the current version.

**Comment by mattrichard** [comment]
> I'd like to move deep-equal to devDependencies and keep the current version.

Sounds good to me. It'll make supporting v12 easier.

**Pull request merged**
