### PR TITLE
make publisher be able to take-in a plain JavaScript object as messag…

### PR DESCRIPTION
**Pull request by kenny-y**
…e to be published

### CODE REVIEW

**Comment by kenny-y** [comment]
This is the kinda precondition of #189 , the purpose is to enable publisher to be able to take-in plain JavaScript objects as arguments. These plain JavaScript objects are easier to be used than ROS message wrapper instances.

**Review by minggangw — APPROVED** [review]
For the file lib/message-translator.js, we'd better use the underscore in the name of source files to align with the existing ones, others LGTM, thanks!

**Comment by kenny-y** [comment]
Push it again to trigger all CIs... AppVeyor failed for the previous push but there was no change to the functionality. So I'd like to trigger it again and see what happens.

**Comment by kenny-y** [comment]
image

AppVeyor works this time but Travis is complaining...

**Comment by kenny-y** [comment]
Finally all CIs work.

**Pull request merged**
