### PR TITLE
Refactor the generator.js

### PR DESCRIPTION
**Pull request by minggangw**
This aims to break down the functions in generator.js and move its
functions to more specific submodules, which are responsible to create
the JavaScript files from .msg/.srv/.action files.

Fix NONE

### CODE REVIEW

**Comment by qiuzhong** [comment]
@minggangw , the Windows CI failed due to the failure of resolving ros2 demo app path on Windows. Could you please change `test/utils.js` line 69 base on your PR #342 from 
`if (fs.existsSync(appendedPath)) {`
to
`if (fs.existsSync(appendedPath) || fs.existsSync(appendedPath + '.exe')) {`

to see if this can work out. I submitted another PR #347 to patch it but found it may break the independence of develop and actionlib branch and is not good. So I'm going to close it.

**Comment by minggangw** [comment]
I will change it when updating this PR

**Comment by minggangw** [comment]
Hi @qiuzhong the CI checks passed.

**Comment by qiuzhong** [comment]
Great!

**Pull request merged**
