### PR TITLE
Add pollForService feature

### PR DESCRIPTION
**Pull request by koonpeng**
I notice rclnodejs blocks indefinitely when doing a service call immediately after creating a client. This is possibly because the service is not ready yet.

This PR adds `isServiceServerAvailable` and `pollForService` method. They aim to provide the same functionality as `wait_for_service` in rclpy. (https://github.com/ros2/rclpy/blob/1cf216dd9ecd4359dc93f317e01b7386d5a36c5a/rclpy/rclpy/client.py#L146)

### CODE REVIEW

**Comment by minggangw** [comment]
Thanks for your contribution! Indeed, we should have these two functions to facilitate developers,  otherwise, they will meet the situation you describe.  Some suggestions:

- Would you please change the method name ```pollForService``` to ```waitForService```, as I prefer to align with `rclpy` naming to reduce confusion.
- About the CIs
  - For Travis-Ci (Unbuntu), there is a problem when installing the dependency base on the latest nightly build, but we can ignore it.
  - For the circleci (macOS), I notice some tests failed. I'm afraid we have to solve this before merging.
- Finally, you could add yourself to the [contributors](https://github.com/RobotWebTools/rclnodejs#contributors) 😄

**Comment by koonpeng** [comment]
Thanks for the comments!

I changed `pollForService` to `waitForService` as suggested. I wan't sure what to name it because `pollForService` gives a better description but I can see how having the same name as rclpy helps users.

For the mac tests, it looks like it fails in `ActionClient status succeed` which this PR shouldn't affect. The 2nd failure seems to log that the publisher is no longer valid. Unfortunately I don't have a mac and I can't reproduce it on Linux. A subsequent run does pass though so it could be a one off error?

**Comment by minggangw** [comment]
> For the mac tests, it looks like it fails in `ActionClient status succeed` which this PR shouldn't affect. The 2nd failure seems to log that the publisher is no longer valid. Unfortunately I don't have a mac and I can't reproduce it on Linux. A subsequent run does pass though so it could be a one off error?

Yes, some tests become flaky at a low rate, so you have to rerun it manually. Once it becomes green and we can land it.

The problem on travis-ci should have been fixed by https://github.com/ros2/ament_cmake_ros/issues/5, you can try to trigger the bot again after there is a newly built package on the ci.ros2.org. Thanks!

**Comment by minggangw** [comment]
As all bots turn green, I create an issue #512 to track this feature and will merge it soon, thanks!

**Comment by minggangw** [comment]
@koonpeng PR has been merged, thanks!

You are always welcome to contribute any new features to this module if you are interested in. Actually, #498 has a detailed summary of the current future absence compared with `rclpy`  and I hope we can offer an alternative to other developers to bridge them into ROS2 😃

**Pull request merged**
