### PR TITLE
[UT]Defer to publish or launch clients

### PR DESCRIPTION
**Pull request by qiuzhong**
Increase timeout to defer to pulish action or launch clients

### CODE REVIEW

**Comment by minggangw** [comment]
#283 landed, please rebase your code and trigger the CI again.

**Comment by minggangw** [comment]
Hi @qiuzhong is this PR ready to be merged?

**Comment by qiuzhong** [comment]
Yes. Please merge it.

**Comment by minggangw** [comment]
Got it, thanks!

**Pull request merged**
